# Generated by Django 3.2.5 on 2021-07-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='borrowedBooks',
            field=models.ManyToManyField(null=True, through='pages.Borrow', to='pages.Book'),
        ),
    ]
