# Generated by Django 3.2.5 on 2021-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_account_borrowedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowStartDate',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
