# Generated by Django 3.2.5 on 2021-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_borrow_borrowstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowStartDate',
            field=models.DateField(auto_now=True),
        ),
    ]
